#!/bin/env bash

#Define the ssh public key
SSH_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNdtrNGtTXe5Tp1EJQop8mOSAuRGLjJ6DW4PqX4wId/Kawz35ESampIqHSOTJmbQ8UlxdJuk0gAXKk3Ncle4safGYqM/VeDK3LN5iAJxf4kcaxNtS3eVxWBE5iF3FbIjOqwxw5Lf5sRa5yXxA8HfWidhbIG5TqKL922hPgsCGABIrXRlfZYeC0FEuPWdr6smOElSVvIXthRWp9cr685KdCI+COxlj1RdVsvIo+zunmLACF9PYdjB2s96Fn0ocD3c5SGLvDOFCyvDojSAOyE70ebIElnskKsDTGwfT4P6jh9OBzTyQEIS2jOaE5RQq4IB4DsMhvbjDSQrP0MdCLgwkN"

# Set path to authorized key files
AUTH_KEYS_FILE="/home/ubuntu/.ssh/authorized_keys"

if [ ! -f "$AUTH_KEYS_FILE" ]; then
    mkdir -p /home/ubuntu/.ssh
    touch $AUTH_KEYS_FILE
    chmod 600 $AUTH_KEYS_FILE
fi

if ! grep -q "$SSH_PUBLIC_KEY" "$AUTH_KEYS_FILE"; then
    echo "$SSH_PUBLIC_KEY" >> $AUTH_KEYS_FILE
fi

chown -R ubuntu:ubuntu /home/ubuntu/.ssh
chmod 700 /home/ubuntu/.ssh
chmod 600 $AUTH_KEYS_FILE
